
CREATE DATABASE numb3rL0ck3r;
EXEC SQL CONNECT TO numb3rL0ck3r;
CREATE ROLE numb3rK33p3r WITH LOGIN PASSWORD '';
CREATE ROLE numb3rK33p3rAdmin WITH LOGIN PASSWORD '';
CREATE ROLE numb3rL0ck3rAdmin WITH LOGIN PASSWORD '';
GRANT SELECT,INSERT,UPDATE,DELETE ON  user to numb3rK33p3r;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL to numb3rK33p3rAdmin;
GRANT ALL PRIVILEGES ON numb3rL0ck3r TO numb3rL0ck3rAdmin;


